name: docker hello world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: login azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: azure login
        run: |
          az acr login --name demo38
        
      - name: build docker image
        run: |
          docker build -t demo38.azurecr.io/hello-python:latest .  #creating my docker image as hellp-python
      
      - name: push docker img to acr
        run: |
          docker push demo38.azurecr.io/hello-python:latest
    
